#!/bin/sh
#
# Inspect java programs
#   ex) ./inspect Quick3way QuickX QuickRnd
#
    ./random.awk 10000 | tee raw.tmp | sort > sorted.tmp
    for a in $*; do
        java -cp :. $a < raw.tmp | awk 'NF==1' > result.tmp
        diff result.tmp sorted.tmp > /dev/null
        if [ $? -eq 0 ]; then
            echo $a
        else
            echo $a unsorted!
        fi
    done
    rm raw.tmp sorted.tmp result.tmp
